# Generated by Django 3.2.4 on 2021-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_barra', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_nac', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('nivel_educacional', models.CharField(max_length=50)),
            ],
        ),
    ]
