# Generated by Django 3.2.4 on 2021-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210606_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.IntegerField(choices=[(1, 'Argentina'), (2, 'Bolivia'), (3, 'Brasil')], default=1),
        ),
    ]
