# Generated by Django 3.2.4 on 2021-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuario_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_educacional',
            field=models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Doctor'), (3, 'Magister'), (4, 'Profesional'), (5, 'Educacion Media'), (6, 'Educacion Basica'), (7, 'Otra')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.IntegerField(choices=[(1, 'Argentina'), (2, 'Bolivia'), (3, 'Brasil'), (4, 'Chile'), (5, 'Colombia'), (6, 'Costa Rica'), (7, 'Cuba'), (8, 'Ecuador'), (9, 'El salvador'), (10, 'Guatemala'), (11, 'Honduras'), (12, 'Mexico'), (13, 'Nicaragua'), (14, 'Panama'), (15, 'Paraguay'), (16, 'Peru'), (17, 'Puerto Rico'), (18, 'Republica Dominicana'), (19, 'Uruguay'), (20, 'Venezuela'), (21, 'Seleccione')], default=21),
        ),
    ]
