# Generated by Django 3.2.4 on 2021-07-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_fantasia', models.CharField(max_length=50)),
                ('correo_institucional_venta', models.EmailField(max_length=50)),
                ('coreo_contacto', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('giro', models.CharField(max_length=50)),
            ],
        ),
    ]
